<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DshLauncher.WebView.Tests</RootNamespace>
    <AssemblyName>DshLauncher.WebView.Tests</AssemblyName>
    <IsTestProject>true</IsTestProject>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DshLauncher.Core/DshLauncher.Core.csproj" />
    <ProjectReference Include="../../src/DshLauncher.WebView/DshLauncher.WebView.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
